import { Metadata } from "next";
import PageHero from "@/components/PageHero";
import ServiceContent from "@/components/ServiceContent";

export const metadata: Metadata = {
  title: "Energie Rinnovabili: Fotovoltaico e Colonnine Ricarica | TF Edilservice Sagl",
  description: "Installazione pannelli fotovoltaici e stazioni di ricarica per veicoli elettrici in Canton Ticino. Verso un futuro sostenibile con energia pulita.",
  keywords: "energie rinnovabili, fotovoltaico, pannelli solari, colonnina ricarica, veicolo elettrico, Ticino",
  openGraph: { title: "Energie Rinnovabili: Fotovoltaico e Colonnine Ricarica | TF Edilservice Sagl", description: "Installazione pannelli fotovoltaici e stazioni di ricarica per veicoli elettrici.", url: "https://www.tf-edilservice.ch/servizi/energie-rinnovabili", type: "website" },
  alternates: { canonical: "https://www.tf-edilservice.ch/servizi/energie-rinnovabili" },
};

const faqData = [
  { question: "Quanto si risparmia con un impianto fotovoltaico?", answer: "Un impianto fotovoltaico può coprire fino al 70-80% del fabbisogno energetico di un'abitazione, generando risparmi significativi sulla bolletta elettrica. In 25-30 anni di vita dell'impianto, il risparmio totale può superare i 50.000 CHF, rendendo l'investimento molto redditizio." },
  { question: "Quali incentivi sono disponibili in Ticino?", answer: "In Canton Ticino sono disponibili incentivi cantonali e federali per l'installazione di impianti fotovoltaici. La Confederazione offre rimborso per l'energia prodotta, mentre il Cantone Ticino contribuisce con incentivi aggiuntivi. Il nostro team vi guida nella richiesta di tutti gli incentivi disponibili." },
  { question: "Le colonnine di ricarica sono compatibili con tutte le auto?", answer: "Sì, le nostre stazioni di ricarica supportano tutti i veicoli elettrici con standard Type 2 e CCS (Combined Charging System), garantendo la massima compatibilità con tutte le marche: Tesla, BMW, Mercedes, Audi, Volkswagen, Hyundai, Kia e molte altre." },
  { question: "Quanto dura un impianto fotovoltaico?", answer: "Gli impianti fotovoltaici moderni hanno una durata stimata di 25-30 anni. I pannelli mantengono circa l'80% della loro efficienza dopo 25 anni. Offriamo garanzie estese sui pannelli e sull'inverter, oltre a contratti di manutenzione." },
  { question: "Cos'è un sistema di accumulo e quando è utile?", answer: "Un sistema di accumulo (batterie) permette di immagazzinare l'energia prodotta in eccesso durante il giorno per utilizzarla di notte o in caso di blackout. È particolarmente utile per massimizzare l'autoconsumo e per chi ha tariffe differenziate." },
  { question: "Qual è la potenza consigliata per un'abitazione residenziale?", answer: "Per un'abitazione residenziale standard in Ticino, consigliamo impianti da 6-10 kWp (chilowatt picco), sufficienti a coprire il fabbisogno energetico di una famiglia. La dimensione dipende dal consumo annuale e dalla disponibilità di spazio sul tetto." },
  { question: "L'installazione richiede modifiche strutturali?", answer: "Generalmente no. I pannelli fotovoltaici vengono installati direttamente sul tetto esistente (tetti inclinati) o su strutture di supporto (tetti piani). L'intervento è poco invasivo e non modifica la struttura dell'edificio." },
  { question: "Posso caricare più veicoli contemporaneamente?", answer: "Sì, è possibile installare stazioni di ricarica multiple con gestione dinamica del carico che distribuisce la potenza disponibile tra i veicoli. Per attività commerciali e condomini offriamo soluzioni scalabili." },
  { question: "Quanto tempo occorre per installare un impianto fotovoltaico?", answer: "Per un'abitazione residenziale, dall'approvazione del progetto all'installazione occorrono circa 2-4 settimane. I tempi dipendono dalla complessità dell'impianto e dalle autorizzazioni necessarie." },
  { question: "Fornite manutenzione degli impianti fotovoltaici?", answer: "Sì, offriamo contratti di manutenzione che includono pulizia dei pannelli, verifica dell'inverter, controllo dei cablaggi e monitoraggio delle performance. La manutenzione periodica garantisce la massima efficienza dell'impianto." }
];

const structuredData = {
  "@context": "https://schema.org",
  "@graph": [
    { "@type": "Service", "name": "Energie Rinnovabili", "description": "Installazione pannelli fotovoltaici e stazioni di ricarica per veicoli elettrici.", "provider": { "@type": "Organization", "name": "TF Edilservice Sagl" }, "areaServed": { "@type": "State", "name": "Canton Ticino" } },
    { "@type": "FAQPage", "mainEntity": faqData.map(faq => ({ "@type": "Question", "name": faq.question, "acceptedAnswer": { "@type": "Answer", "text": faq.answer } })) }
  ]
};

export default function EnergieRinnovabiliPage() {
  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} />
      <PageHero iconName="Sun" title="Energie Rinnovabili" subtitle="Impianti fotovoltaici e stazioni di ricarica per veicoli elettrici. Verso un futuro sostenibile con energia pulita in Canton Ticino." breadcrumb={[{ label: "Home", href: "/" }, { label: "Servizi", href: "/servizi" }, { label: "Energie Rinnovabili" }]} imageUrl="/images/servizi/energie-rinnovabili.jpg" keyPoints={[{ text: "Risparmio energetico fino all'80%" }, { text: "Assistenza per incentivi cantonali e federali" }, { text: "Colonnine ricarica per tutti i veicoli elettrici" }, { text: "Sistemi di accumulo per massimizzare l'autoconsumo" }, { text: "25-30 anni di garanzia sui pannelli" }]} />
      <ServiceContent definition="Le energie rinnovabili comprendono tecnologie che sfruttano fonti naturali inesauribili come il sole. L'installazione di impianti fotovoltaici e stazioni di ricarica per veicoli elettrici permette di ridurre i costi energetici, diminuire le emissioni e contribuire alla transizione verso un futuro sostenibile. In un contesto di aumento dei costi energetici, investire nelle rinnovabili significa tutelare il proprio futuro finanziario e l'ambiente." targetAudience={[{ title: "Residenziale", description: "Case e appartamenti. Risparmio energetico e indipendenza.", slug: "residenziale" }, { title: "Commerciale", description: "Aziende e uffici. Energie verdi e immagine sostenibile.", slug: "commerciale" }, { title: "Condomini", description: "Condomini condivisi. Gestione intelligente e costi ridotti.", slug: "condomini" }]} features={[{ title: "Impianti Fotovoltaici", description: "Progettazione e installazione di impianti solari per produzione di energia elettrica.", slug: "impianti-fotovoltaici" }, { title: "Accumulo Energia", description: "Sistemi di accumulo con batterie per massimizzare l'autoconsumo.", slug: "accumulo-energia" }, { title: "Colonnine Ricarica", description: "Installazione stazioni di ricarica per veicoli elettrici, domestiche e aziendali.", slug: "colonnine-ricarica" }, { title: "Efficientamento Energetico", description: "Consulenza per la riduzione dei consumi e ottimizzazione energetica.", slug: "efficientamento-energetico" }, { title: "Pratiche Incentivi", description: "Assistenza nella richiesta di incentivi cantonali e federali.", slug: "pratiche-incentivi" }, { title: "Monitoraggio", description: "Sistemi di monitoraggio remoto delle performance dell'impianto.", slug: "monitoraggio" }, { title: "Manutenzione", description: "Servizi di pulizia e manutenzione per massimizzare la resa.", slug: "manutenzione" }, { title: "Inverter e Optimizer", description: "Installazione di inverter di ultima generazione e optimizer.", slug: "inverter-e-optimizer" }, { title: "Tetti Solari", description: "Integrazione architettonica con tetti solari innovativi.", slug: "tetti-solari" }, { title: "Consulenza Energetica", description: "Analisi dei consumi e studio di fattibilità personalizzato.", slug: "consulenza-energetica" }]} processSteps={[{ step: 1, title: "Analisi", description: "Studio di fattibilità e consumi" }, { step: 2, title: "Progettazione", description: "Progetto tecnico personalizzato" }, { step: 3, title: "Installazione", description: "Posa impianto e colonnine" }, { step: 4, title: "Attivazione", description: "Allaccio e collaudo" }, { step: 5, title: "Monitoraggio", description: "Assistenza continua" }]} benefits={["Risparmio sulla bolletta fino all'80%", "Contributo concreto all'ambiente", "Incentivi e detrazioni fiscali", "Indipendenza energetica", "Valore aggiunto all'immobile", "25 anni di garanzia"]} faq={faqData} serviceName="Energie Rinnovabili" parentSlug="energie-rinnovabili" />
    </>
  );
}